from tkinter import*
from tkinter import ttk
from tkinter import messagebox
from dailydb import Database

win=Tk()
win.title("roopa")
win.geometry("500x500")
win.config(bg="blue")
db=Database("roopa20091.db")
def getdata(event):
    row1=tv.focus()
    data=tv.item(row1)
    global row
    row=data["values"]
     #print(row)
    e1.insert(0,row[1])
    e2.insert(0,row[2])
    e3.insert(0,row[3])
    c1.set("",row[4])
    c2.set("", row[5])
    c3.set("", row[6])
def update():

    db.update(e1.get(),e2.get(),e3.get(),c1.get(),c2.get(),c3.get())
    messagebox.showinfo("added", " updated")
    clear()
    displayAll()
def insert():
    db.insert(e1.get(),e2.get(),e3.get(),c1.get(),c2.get(),c3.get())
    messagebox.showinfo("Success", "added")
    clear()
    displayAll()
def remove():
    db.remove(row[0])
    clear()
    displayAll()
def clear():
    e1.delete(0,END)
    e2.delete(0, END)
    e3.delete(0, END)
    c1.set(0,"")
    c2.set(0, "")
    c3.set(0, "")
def displayAll():
    tv.delete(*tv.get_children())
    for row in db.fetch():
        tv.insert("", END, values=row)



f1=Frame(win,bg="blue")
f1.pack(side=TOP,fill=X)
l1=Label(f1,text="DAILY EXPENSES",font=("calibri",18,"bold"),bg="#535c68",fg="white")
l1.grid(row=0,column=2,padx=10,pady=10)
l2=Label(f1,text="NAME")
l2.grid(row=1,column=0,padx=10,pady=10)
e1=Entry(f1,width=20)
e1.grid(row=1,column=1,padx=10,pady=10,sticky="W")
l3=Label(f1,text="MOBNO")
l3.grid(row=1,column=2,padx=10,pady=10)
e2=Entry(f1,width=20)
e2.grid(row=1,column=3,padx=10,pady=10,sticky="W")
l4=Label(f1,text="GMAIL")
l4.grid(row=2,column=0,padx=10,pady=10)
e3=Entry(f1,width=20)
e3.grid(row=2,column=1,padx=10,pady=10,sticky="W")
l5=Label(f1,text="PRIZE")
l5.grid(row=2,column=2,padx=10,pady=10)
c1=ttk.Combobox(f1,width=20)
c1["values"]=("1000","5000","10000")
c1.grid(row=2,column=3,padx=10,pady=10,sticky="W")
l6=Label(f1,text="PAYMENTTYPE")
l6.grid(row=3,column=0,padx=10,pady=10)
c2=ttk.Combobox(f1,width=20)
c2["values"]=("PHONEPAY","CASH","GPAY")
c2.grid(row=3,column=1,padx=10,pady=10,sticky="W")
l7=Label(f1,text="CATAGORY")
l7.grid(row=3,column=2,padx=10,pady=10)
c3=ttk.Combobox(f1,width=20)
c3["values"]=("DRESS","GLOSSARY","GIFTS")
c3.grid(row=3,column=3,padx=10,pady=10,sticky="W")
f2=Frame(f1,bg="#535c68")
f2.grid(row=4,columnspan=4,padx=10,pady=10,sticky="W")
b1=Button(f2,text="INSERT",command=insert)
b1.grid(row=4,column=0,padx=10,pady=10,sticky="W")
b1=Button(f2,text="UPDATE",command=update)
b1.grid(row=4,column=1,padx=10,pady=10,sticky="W")
b1=Button(f2,text="DELETE",command=remove)
b1.grid(row=4,column=2,padx=10,pady=10,sticky="W")
b1=Button(f2,text="CLEAR",command=clear)
b1.grid(row=4,column=3,padx=10,pady=10,sticky="W")
tf=Frame(win,bg="#ecf0f1")
tf.place(x=0,y=500,width=1400,height=500)
style=ttk.Style()
style.configure("mystyle.Treeview",font=("calibri",16),rowheight=50)
style.configure("mystyle.Treeview.Heading",font=("calibri",18,"bold"))
tv=ttk.Treeview(tf,columns=(1,2,3,4,5,6),style="mystyle.Treeview")

tv.heading("1",text="ID")
tv.column("1",width=3,anchor=CENTER)
tv.heading("2",text="NAME")
tv.column("2",width=3,anchor=CENTER)
tv.heading("3",text="MOBNO")
tv.column("3",width=3,anchor=CENTER)
tv.heading("4",text="GMAIL")
tv.column("4",width=3,anchor=CENTER)
tv.heading("5",text="PRIZE")
tv.column("5",width=3,anchor=CENTER)
tv.heading("6",text="PAYMENTTYPE")
tv.column("6",width=3,anchor=CENTER)
tv.heading("6",text="CATAGORY")
tv.column("6",width=3,anchor=CENTER)
tv['show'] = "headings"
tv.bind("<ButtonRelease-1>",getdata)
tv.pack(fill=X)
displayAll()


win.mainloop()